MovieHunter/MovieHunter/urls.py
from django.contrib import admin
from django.urls import path, include
from movie_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
]

MovieHunter/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register', views.register_view, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

MovieHunter/accounts/models.py
from django.db import models

# Create your models here.

MovieHunter/movie_app/models.py
from django.db import models

# Create your models here.
class Movie:
    name = ""
    comments = 0
    image = ""

MovieHunter/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text="Required. Inform a valid email")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class LoginForm(AuthenticationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password', )

MovieHunter/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import redirect, render
from django.contrib import messages


# Create your views here.
def  register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
        return render(request, 'accounts/register.html', context={'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalides Credentials')
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', context = {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')
        

MovieHunter/movie_app/views.py
from django.shortcuts import render
from .models import Movie

# Create your views here.
def index(request):
    movie1 = Movie()
    movie1.name = 'X-MAN'
    movie1.comments = 112
    movie1.image = 'movie1.jpg'
    movie2 = Movie()
    movie2.name = 'SPIDER MAN 2'
    movie2.comments = 7
    movie2.image = 'movie2.jpg'
    movie3 = Movie()
    movie3.name = 'SPIDER MAN 3'
    movie3.comments = 24
    movie3.image = 'movie3.jpg'

    movies = [movie1, movie2, movie3]


    template_name = 'movie_app/index.html'
    context = {'movies': movies}
    return render(request, template_name, context)

MovieHunter/accounts/templates/accounts/login.html
{% extends "movie_app/index.html" %}
{% block content %}
<div class="container text-center">
  <h2>Signin</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
    
    {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %}
  </form>
</div>
{% endblock content %}

{% block news %}{% endblock news %}

{% block comming %}{% endblock comming %}

MovieHunter/accounts/templates/accounts/register.html
<h1>Registration page</h1>

<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>

MovieHunter/movie_app/templates/movie_app/index.html
<!DOCTYPE html
{% load static %}
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>MovieHunter</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
  <script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
  <!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
</head>

<body>
  <!-- START PAGE SOURCE -->
  <div id="shell">
    <div id="header">
      <h1 id="logo"><a href="#">MovieHunter</a></h1>
      <div class="social"> <span>FOLLOW US ON:</span>
        <ul>
          <li><a class="twitter" href="#">twitter</a></li>
          <li><a class="facebook" href="#">facebook</a></li>
          <li><a class="vimeo" href="#">vimeo</a></li>
          <li><a class="rss" href="#">rss</a></li>
        </ul>
      </div>
      <div id="navigation">
        <ul>
          <li><a class="active" href="#">HOME</a></li>
          <li><a href="#">NEWS</a></li>
          <li><a href="#">IN THEATERS</a></li>
          <li><a href="#">COMING SOON</a></li>
          <li><a href="#">CONTACT</a></li>
          {% if user.is_authenticated %}
            <li>Hello, {{ user.username | upper }}</li>
            <li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a href="{% url 'accounts:register' %}">REGISTER</a></li>
            <li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
          {% endif %}
        </ul>
      </div>
      <div id="sub-navigation">
        <ul>
          <li><a href="#">SHOW ALL</a></li>
          <li><a href="#">LATEST TRAILERS</a></li>
          <li><a href="#">TOP RATED</a></li>
          <li><a href="#">MOST COMMENTED</a></li>
        </ul>
        <div id="search">
          <form action="#" method="get" accept-charset="utf-8">
            <label for="search-field">SEARCH</label>
            <input type="text" name="search field" value="Enter search here" id="search-field"
              class="blink search-field" />
            <input type="submit" value="GO!" class="search-button" />
          </form>
        </div>
      </div>
    </div>
    <div id="main">
      {% block content %}
      <div id="content">
        <div class="box">
          <div class="head">
            <h2>LATEST TRAILERS</h2>
            <p class="text-right"><a href="#">See all</a></p>
          </div>
          {% for movie in movies %}
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">{{ movie.name }}</span></span> <a href="#"><img
                  src="{% static 'css/images/' %}{{ movie.image }}" alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">{{ movie.comments }}</span>
            </div>
          </div>
          {% endfor %}
          <div class="cl">&nbsp;</div>
        </div>
        <div class="box">
          <div class="head">
            <h2>TOP RATED</h2>
            <p class="text-right"><a href="#">See all</a></p>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">TRANSFORMERS</span></span> <a href="#"><img
                  src='{% static "css/images/movie7.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">MAGNETO</span></span> <a href="#"><img
                  src='{% static "css/images/movie8.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">KUNG FU PANDA</span></span> <a href="#"><img
                  src='{% static "css/images/movie9.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">EAGLE EYE</span></span> <a href="#"><img
                  src='{% static "css/images/movie10.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">NARNIA</span></span> <a href="#"><img
                  src='{% static "css/images/movie11.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie last">
            <div class="movie-image"> <span class="play"><span class="name">ANGELS &amp; DEMONS</span></span> <a
                href="#"><img src='{% static "css/images/movie12.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="cl">&nbsp;</div>
        </div>
        <div class="box">
          <div class="head">
            <h2>MOST COMMENTED</h2>
            <p class="text-right"><a href="#">See all</a></p>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">HOUSE</span></span> <a href="#"><img
                  src='{% static "css/images/movie13.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">VACANCY</span></span> <a href="#"><img
                  src='{% static "css/images/movie14.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">MIRRORS</span></span> <a href="#"><img
                  src='{% static "css/images/movie15.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">THE KINGDOM</span></span> <a href="#"><img
                  src='{% static "css/images/movie16.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">MOTIVES</span></span> <a href="#"><img
                  src='{% static "css/images/movie17.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="movie last">
            <div class="movie-image"> <span class="play"><span class="name">THE PRESTIGE</span></span> <a href="#"><img
                  src='{% static "css/images/movie18.jpg" %}' alt="" /></a> </div>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span>
            </div>
          </div>
          <div class="cl">&nbsp;</div>
        </div>
      </div>  
      {% endblock content %}
      {% block news %}
      <div id="news">
        <div class="head">
          <h3>NEWS</h3>
          <p class="text-right"><a href="#">See all</a></p>
        </div>
        <div class="content">
          <p class="date">12.04.09</p>
          <h4>Disney's A Christmas Carol</h4>
          <p>&quot;Disney's A Christmas Carol,&quot; a multi-sensory thrill ride re-envisioned by Academy
            Award&reg;-winning filmmaker Robert Zemeckis, captures... </p>
          <a href="#">Read more</a>
        </div>
        <div class="content">
          <p class="date">11.04.09</p>
          <h4>Where the Wild Things Are</h4>
          <p>Innovative director Spike Jonze collaborates with celebrated author Maurice Sendak to bring one of the most
            beloved books of all time to the big screen in &quot;Where the Wild Things Are,&quot;...</p>
          <a href="#">Read more</a>
        </div>
        <div class="content">
          <p class="date">10.04.09</p>
          <h4>The Box</h4>
          <p>Norma and Arthur Lewis are a suburban couple with a young child who receive an anonymous gift bearing fatal
            and irrevocable consequences.</p>
          <a href="#">Read more</a>
        </div>
      </div>
      {% endblock news %}
      {% block comming %}
      <div id="coming">
        <div class="head">
          <h3>COMING SOON<strong>!</strong></h3>
          <p class="text-right"><a href="#">See all</a></p>
        </div>
        <div class="content">
          <h4>The Princess and the Frog </h4>
          <a href="#"><img src='{% static "css/images/coming-soon1.jpg" %}' alt="" /></a>
          <p>Walt Disney Animation Studios presents the musical &quot;The Princess and the Frog,&quot; an animated
            comedy set in the great city of New Orleans...</p>
          <a href="#">Read more</a>
        </div>
        <div class="cl">&nbsp;</div>
        <div class="content">
          <h4>The Princess and the Frog </h4>
          <a href="#"><img src='{% static "css/images/coming-soon2.jpg" %}' alt="" /></a>
          <p>Walt Disney Animation Studios presents the musical &quot;The Princess and the Frog,&quot; an animated
            comedy set in the great city of New Orleans...</p>
          <a href="#">Read more</a>
        </div>
      </div>
      {% endblock comming %}
      <div class="cl">&nbsp;</div>
    </div>
    <div id="footer">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
      <div style="clear:both;"></div>
    </div>
  </div>
  <!-- END PAGE SOURCE -->
</body>

</html>